version: '3.7'

volumes:
  database-data-volume: # named volumes can be managed easier using docker-compose

services:
  database:
    image: "postgis/postgis" # use latest official postgres version
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - database-data-volume:/var/lib/postgresql/data/ # persist data even if container shuts down
      
  backend:
    image: 'enszyk/how-money-api:0.1.3'
    restart: unless-stopped
    ports:
      - 5000:80
    depends_on:
      - "database"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      Database__ZPI__ConnectionString: "User ID=admin; Password=admin; Server=database;Port=5432;Database=zpi;Integrated Security=true; Pooling=true;"
      Database__ZPI__EnableAutomaticMigration: "True"
      Database__ZPI__PostgresApiVersion: 12.3